name    'saz-rsyslog'
version '3.1.0'
source 'https://github.com/saz/puppet-rsyslog.git'
author 'saz'
license 'Apache License, Version 2.0'
summary 'Manage rsyslog client and server'
description 'Manage rsyslog client and server via Puppet'
project_page 'https://github.com/saz/puppet-rsyslog'
