name    'saz-rsyslog'
version '2.0.1'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'Manage rsyslog client and server'
description 'Manage rsyslog client and server via Puppet'
project_page 'https://github.com/saz/puppet-rsyslog'
